### ISSUE TITLE
Question.

### ISSUE THREAD

**Issue by NeilTohno** [jammln/AsioWinamp#1]
Hello.
The "out_asio(x64).exe" is not compiled ?
What‘s the changes compared with the previous version ?

You can discuss with other people here:
http://forums.winamp.com/forumdisplay.php?f=8

Thanks.

**Comment by jammln** [comment]
Hi,
The changes made to the plugin was to enforce gapless mode so music plays without having pauses for seamless transitions between songs. Also, I removed monitor mode as I didn't need it and was extra bloat to the program. Other than that it is a fresh re-compile. There is the out_asio(x64).exe and dll in the repo. You can also compile it yourself if you wish. I haven't done any work on this for around a year so my memory is a little hazy.
Thanks.

**Comment by NeilTohno** [comment]
I am not a programmer , I don't kown any programming language. May you help me to compile the out_asio(x64).exe file, if you are not busy？
_Thanks._

**Comment by jammln** [comment]
If you download the repo, there is already the compiled exe files as well as the dll file.

**Comment by NeilTohno** [comment]
<a href="http://tinypic.com?ref=254vcls" target="_blank"><img src="http://i63.tinypic.com/254vcls.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by jammln** [comment]
I haven't worked on it in a year and I know it doesn't work on some systems. There is a new version being released on http://forums.winamp.com/showthread.php?t=379617 which is probably a lot better than this version. Sorry for the issues you are having with getting it to work.
